# Generated by Django 2.1b1 on 2018-08-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userMobileNo', models.IntegerField(max_length=10)),
                ('userCurrentPoints', models.IntegerField(max_length=10)),
            ],
        ),
    ]
