# Generated by Django 2.1b1 on 2018-08-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userCurrentPoints',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userMobileNo',
            field=models.IntegerField(),
        ),
    ]
