# Generated by Django 2.1b1 on 2018-08-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpage', '0002_auto_20180804_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=250)),
                ('productDesc', models.CharField(max_length=250)),
                ('productWt', models.CharField(max_length=10)),
                ('productPrice', models.CharField(max_length=10)),
            ],
        ),
    ]
