# Generated by Django 2.1b1 on 2018-08-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpage', '0003_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='productDesc',
            new_name='productQty',
        ),
    ]
